/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HomeRouteImport } from './routes/home/route'

// Create/Update Routes

const HomeRouteRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/home/route.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/home': typeof HomeRouteRoute
}

export interface FileRoutesByTo {
  '/home': typeof HomeRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/home': typeof HomeRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/home'
  fileRoutesByTo: FileRoutesByTo
  to: '/home'
  id: '__root__' | '/home'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  HomeRouteRoute: typeof HomeRouteRoute
}

const rootRouteChildren: RootRouteChildren = {
  HomeRouteRoute: HomeRouteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/home"
      ]
    },
    "/home": {
      "filePath": "home/route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
